### ISSUE TITLE
warp scales are not constrainted to be positive

### ISSUE THREAD

**Issue by poolio** [ganguli-lab/twpca#14]
this can result in invalid warping functions with negative slope

**Comment by ahwillia** [comment]
Use `tf.softplus(tau_scale)` or `tau_scale**2` ? I would prefer the latter since we initialize the scales as `1.0` and `1**2 = 1` so it would require no further changes to the code.

**Comment by nirum** [comment]
a monotonic function seems better to me, plus `softplus(1.0) ~= 1.0` regardless

**Comment by ahwillia** [comment]
Ok PR is here: https://github.com/ganguli-lab/twpca/pull/16/commits/f12a70edce62a501f476e2b853a6fe2977cc16fd
